### ISSUE TITLE
Calendar Selection Style similar to iPhone Expedia app

### ISSUE THREAD

**Issue by ajaysharmalike** [devinross/tapkulibrary#171]
How can I modify the calendar class to allow user to choose the dates within Range.There is a nice intuitive way to allow user to choose the dates in between.
How this can be achieved using the Tapku library. It has really got such a smooth animation using CALayer class.

Thanks,

**Comment by rajsahu81** [comment]
https://github.com/phaibin/Kal

I want to use this Calendar but given code, I'm not getting how to use in my app because this code is not in running mode so that I can check what is the flow of code.

Please help guys.
