### ISSUE TITLE
Mark event to Daily / Weekly / Monthly / Yearly

### ISSUE THREAD

**Issue by mital87** [devinross/tapkulibrary#264]
Hello,

i have create event on 1st September, 2013 for weekly intervals. so my mark date are 1, 8, 15, 22, 29.... so how can i implement this thing using this library. i am stuck at this point. which method of your library help me to resolve this issue. please help me as soon as possible.

Thank you so much in advance.....

**Comment by matrosovDev** [comment]
yea the same question http://stackoverflow.com/users/587415/matrosov-alexander )
