### ISSUE TITLE
Tapku calendar was rejected by apple review for the first time. 

### ISSUE THREAD

**Issue by kaitmania** [devinross/tapkulibrary#303]
My app (100 days miracle) was rejected today for the first time because it uses tapku calendar and the appearance violates Apple's Trademarks and Copyright. I've never thought this would happen. :(

Here is the Apple's comment.
Your app does not comply with the Guidelines for Using Apple's Trademarks and Copyrights. Specifically, your app includes:
- one or more Apple trademark images - or likenesses of Apple trademark images. Specifically, your app displays calendar UI of iOS.

**Comment by richardoti** [comment]
Could you provide more details, which part of the calendar have you used? The DayView or Month View?

**Comment by kaitmania** [comment]
@richardoti The MonthView of tapku library is very similar to Apple's. That's why I chose tapku. But Apple began to issue the copiness of their calendar UI design, which they hadn't before.

**Comment by devinross** [comment]
@kaitmania I've seen Apple reject apps for weirder reasons. I'd suggest trying to resubmit and it'll probably get approved.
